/* DOLDOL HOME STEP 2 — HUD final */
(function(){
if(window.__doldolHomeClean)return;window.__doldolHomeClean=true;
const $=id=>document.getElementById(id);
window.__doldolResources=window.__doldolResources||{get gems(){return Math.max(0,Number(localStorage.getItem("doldol_gems_v1")||"980")||0)},setGems(v){localStorage.setItem("doldol_gems_v1",String(Math.max(0,Number(v)||0)));sync()}};
function info(){let id="doldol",name="돌돌이",face="🐥",level=1,xp=0,next=50;try{id=localStorage.getItem("doldol_character_v1")||id;if(window.__duckGetSelectedCharacter){const c=window.__duckGetSelectedCharacter();if(c){id=c.id||id;name=c.name||name;face=c.face||face}}if(window.__duckCharacterProgress){const p=window.__duckCharacterProgress(id);if(p){level=p.level||1;xp=p.xp||0;next=p.next||50}}}catch(e){}return{id,name,face,level,xp,next}}
function sync(){const c=info(),set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set("homePlayerAvatar",c.face);set("homePlayerName",c.name);set("homePlayerLevel","Lv."+c.level);set("lobbyCoins",(window.__duckWallet?window.__duckWallet.coins:0).toLocaleString());set("homeGems",window.__doldolResources.gems.toLocaleString());const x=$("homePlayerXp");if(x)x.style.width=Math.min(100,c.xp/Math.max(1,c.next)*100)+"%"}
window.__doldolSyncHomeHud=sync;
function rebuild(){const l=$("gameLobby");if(!l||l.dataset.cleanHome==="1")return!!l;const ids=["lobbyStart","lobbyStages","lobbyGrowth","lobbyGear","lobbyShop","lobbyBook","lobbySettings"],saved=ids.map($).filter(Boolean);if(!$("lobbyStart"))return false;saved.forEach(e=>e.remove());l.replaceChildren();l.className="doldolHomeClean";l.dataset.cleanHome="1";
const h=document.createElement("header");h.className="ddHomeHud";h.innerHTML=`<div class="ddProfile"><div class="ddAvatar" id="homePlayerAvatar">🐥</div><div class="ddProfileText"><b id="homePlayerName">돌돌이</b><span id="homePlayerLevel">Lv.1</span><div class="ddXp"><i id="homePlayerXp"></i></div></div></div><div class="ddResources"><div class="ddRes ddCore"><img src="./assets/doldol_stone_core.png" alt="돌핵"><b id="lobbyCoins">0</b><button class="ddPlus" id="homeCorePlus" aria-label="돌핵 추가">+</button></div><div class="ddRes"><span class="ddGem">💎</span><b id="homeGems">980</b><button class="ddPlus" id="homeGemPlus" aria-label="보석 추가">+</button></div></div>`;l.appendChild(h);
saved.forEach(e=>{if(e.id==="lobbySettings"){e.className="ddSettings";e.innerHTML="⚙"}else{e.className="homeControl";e.innerHTML=""}l.appendChild(e)});sync();return true}
const st=document.createElement("style");st.id="doldol-home-clean-css";st.textContent=`
#gameLobby.doldolHomeClean{position:fixed!important;inset:0!important;width:100%!important;height:100dvh!important;margin:0!important;padding:0!important;overflow:hidden!important;background:url('./assets/home_base_bg.png') center/cover no-repeat!important;z-index:20!important;font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important}
#gameLobby.doldolHomeClean.hidden{display:none!important}#gameLobby .homeControl{display:none!important}
#gameLobby .ddHomeHud{position:absolute;left:14px;right:76px;top:max(14px,env(safe-area-inset-top));height:52px;display:flex;align-items:center;gap:8px;z-index:30;color:#fff}
#gameLobby .ddProfile{height:48px;min-width:130px;display:flex;align-items:center;gap:7px;padding:4px 9px 4px 5px;border:1px solid #ffffff55;border-radius:17px;background:#121d24d9;box-sizing:border-box;box-shadow:0 4px 12px #0005}
#gameLobby .ddAvatar{width:38px;height:38px;display:grid;place-items:center;border-radius:12px;background:#f7c94a;font-size:23px;border:2px solid #fffd;box-sizing:border-box}
#gameLobby .ddProfileText{display:flex;flex-direction:column;min-width:69px;line-height:1.05}#gameLobby .ddProfileText b{font-size:12px;white-space:nowrap}#gameLobby .ddProfileText span{font-size:10px;color:#fff;margin-top:3px;font-weight:800}
#gameLobby .ddXp{width:100%;height:5px;margin-top:5px;background:#ffffff2b;border-radius:5px;overflow:hidden}#gameLobby .ddXp i{display:block;height:100%;background:#ffd34e;border-radius:5px}
#gameLobby .ddResources{margin-left:auto;display:flex;gap:7px;align-items:center}
#gameLobby .ddRes{height:40px;min-width:96px;display:flex;align-items:center;gap:5px;padding:0 5px 0 7px;border-radius:14px;background:#123143e8;border:1px solid #ffffff42;box-shadow:0 4px 11px #0004;box-sizing:border-box;white-space:nowrap}
#gameLobby .ddRes b{font-size:14px;margin-left:auto}.ddCore img{width:37px;height:37px;object-fit:contain;display:block}.ddGem{font-size:18px}
#gameLobby .ddPlus{width:25px!important;height:25px!important;min-width:25px!important;padding:0!important;margin:0!important;border:0!important;border-radius:50%!important;background:#2196df!important;color:#fff!important;font-size:22px!important;font-weight:900!important;line-height:25px!important;display:grid!important;place-items:center!important;box-shadow:none!important}
#gameLobby .ddSettings{position:absolute!important;right:4px!important;top:max(18px,env(safe-area-inset-top))!important;width:39px!important;height:39px!important;display:grid!important;place-items:center!important;padding:0!important;border-radius:14px!important;border:1px solid #ffffff44!important;background:#123143e8!important;color:#fff!important;font-size:19px!important;z-index:31!important;box-shadow:0 4px 11px #0004!important}
@media(max-width:390px){#gameLobby .ddHomeHud{left:8px;right:68px;gap:4px}#gameLobby .ddProfile{min-width:118px;padding-right:5px}#gameLobby .ddRes{min-width:84px;padding-left:5px;gap:3px}#gameLobby .ddRes b{font-size:13px}.ddCore img{width:33px;height:33px}#gameLobby .ddPlus{width:24px!important;height:24px!important;min-width:24px!important;font-size:19px!important}}
`;document.head.appendChild(st);
const old=window.__duckSyncLobby;window.__duckSyncLobby=function(){if(typeof old==="function")try{old.apply(this,arguments)}catch(e){}sync()};if(!rebuild()){const mo=new MutationObserver(()=>{if(rebuild())mo.disconnect()});mo.observe(document.documentElement,{childList:true,subtree:true})}window.addEventListener("storage",sync);
})();